version: "3"
services:
    backend:
      build:
        context: blimp/
    frontend:
      build:
        context: client/
      depends_on:
        - backend
      links:
        - backend
      ports:
        - "80:3000"
